### ISSUE TITLE
something about the dataset

### ISSUE THREAD

**Issue by Edison0521** [hyperair/fptree#2]
Dear Mr.Chou
    Excuse me to write this to ask something about the mushroom.dat in the dataset.
    My problem is I am confused in the first line is the attribute or the value.
    Please forgive my poor English.
                                                                                                          Thank you

**Comment by hyperair** [comment]
Hi, this was homework during my university course and I don't recall what this was about or what the datasets were either. Sorry I can't be of help

**Comment by hyperair** [comment]
I've added docs, see the `README.md` for more details

**Comment by Edison0521** [comment]
> Hi, this was homework during my university course and I don't recall what this was about or what the datasets were either. Sorry I can't be of help

Thank you for your reply.I had finished the works about that problems,and I am appricate for that.
